from typing import List
from app.models import Deal, DealCategory


DEALS: List[Deal] = [
    # ===== ELECTRONICS =====
    Deal(
        id=1,
        title="Cuffie Wireless Premium",
        description="Cuffie over-ear noise cancelling di alta qualità, ideali per musica, film e lavoro in ambiente tecnologico",
        price=89.99,
        original_price=179.99,
        discount=50,
        category=DealCategory.electronics,
        image_url="https://example.com/headphones-premium.jpg",
        url="https://example.com/deal/1",
    ),
    Deal(
        id=2,
        title="Set Gadget Tecnologici da Scrivania",
        description="Kit di accessori tecnologia per ufficio con hub USB-C, supporto smartphone e lampada LED minimal per postazione digitale",
        price=49.90,
        original_price=99.90,
        discount=50,
        category=DealCategory.electronics,
        image_url="https://example.com/desk-tech-kit.jpg",
        url="https://example.com/deal/2",
    ),
    Deal(
        id=3,
        title="Mini Proiettore Portatile HD",
        description="Proiettore tascabile per film, presentazioni e gaming, perfetto per setup multimediale tecnologico",
        price=129.00,
        original_price=259.00,
        discount=50,
        category=DealCategory.electronics,
        image_url="https://example.com/mini-projector.jpg",
        url="https://example.com/deal/3",
    ),
    Deal(
        id=4,
        title="Smartwatch Fitness & Notifiche",
        description="Orologio intelligente con monitoraggio attività, notifiche smartphone e quadranti digitali per uno stile di vita tech",
        price=79.90,
        original_price=159.90,
        discount=50,
        category=DealCategory.electronics,
        image_url="https://example.com/smartwatch-fitness.jpg",
        url="https://example.com/deal/4",
    ),
    Deal(
        id=5,
        title="Tastiera Meccanica Retroilluminata",
        description="Tastiera meccanica compatta con illuminazione RGB, ideale per sviluppatori, gamer e appassionati di tecnologia",
        price=89.90,
        original_price=179.90,
        discount=50,
        category=DealCategory.electronics,
        image_url="https://example.com/mechanical-keyboard.jpg",
        url="https://example.com/deal/5",
    ),
    Deal(
        id=6,
        title="Mouse Ergonomico Wireless",
        description="Mouse senza fili con sensore preciso e design ergonomico per postazioni tech da lavoro o gaming",
        price=39.90,
        original_price=79.90,
        discount=50,
        category=DealCategory.electronics,
        image_url="https://example.com/ergonomic-mouse.jpg",
        url="https://example.com/deal/6",
    ),
    Deal(
        id=7,
        title="Cuffie Gaming Surround 7.1",
        description="Cuffie con tecnologia surround per videogiochi, microfono regolabile e audio immersivo per setup da gaming",
        price=69.90,
        original_price=139.90,
        discount=50,
        category=DealCategory.electronics,
        image_url="https://example.com/gaming-headset.jpg",
        url="https://example.com/deal/7",
    ),
    Deal(
        id=8,
        title="Docking Station USB-C Multiporta",
        description="Stazione di espansione per laptop con porte HDMI, USB e rete, perfetta per postazione tecnologia da ufficio",
        price=59.90,
        original_price=119.90,
        discount=50,
        category=DealCategory.electronics,
        image_url="https://example.com/usb-c-dock.jpg",
        url="https://example.com/deal/8",
    ),
    Deal(
        id=9,
        title="Lampada da Lettura Smart",
        description="Lampada da tavolo con controllo touch, modalità lettura e ricarica wireless per dispositivi tecnologici",
        price=44.90,
        original_price=89.90,
        discount=50,
        category=DealCategory.electronics,
        image_url="https://example.com/smart-reading-lamp.jpg",
        url="https://example.com/deal/9",
    ),
    Deal(
        id=10,
        title="Altoparlante Bluetooth Compatto",
        description="Speaker wireless portatile con audio potente, ideale per chi ama gadget tecnologici da viaggio",
        price=39.90,
        original_price=79.90,
        discount=50,
        category=DealCategory.electronics,
        image_url="https://example.com/compact-speaker.jpg",
        url="https://example.com/deal/10",
    ),

    # ===== BEAUTY =====
    Deal(
        id=11,
        title="Crema Viso Rigenerante Notte",
        description="Crema viso nutriente con ingredienti naturali, ideale per skincare serale e pelle secca",
        price=27.99,
        original_price=54.99,
        discount=49,
        category=DealCategory.beauty,
        image_url="https://example.com/face-cream-night.jpg",
        url="https://example.com/deal/11",
    ),
    Deal(
        id=12,
        title="Siero Vitamina C Illuminante",
        description="Siero viso con vitamina C per routine skincare, effetto luminosità e texture leggera",
        price=32.99,
        original_price=65.99,
        discount=50,
        category=DealCategory.beauty,
        image_url="https://example.com/serum-vitamin-c.jpg",
        url="https://example.com/deal/12",
    ),
    Deal(
        id=13,
        title="Maschera Idratante Profonda",
        description="Maschera viso per idratazione intensa, ideale per pelle stressata e routine bellezza serale",
        price=19.99,
        original_price=39.99,
        discount=50,
        category=DealCategory.beauty,
        image_url="https://example.com/hydrating-mask.jpg",
        url="https://example.com/deal/13",
    ),
    Deal(
        id=14,
        title="Olio Corpo Nutriente",
        description="Olio corpo leggero con fragranza delicata, perfetto per chi ama prodotti beauty naturali",
        price=22.99,
        original_price=45.99,
        discount=50,
        category=DealCategory.beauty,
        image_url="https://example.com/body-oil.jpg",
        url="https://example.com/deal/14",
    ),
    Deal(
        id=15,
        title="Set Spazzole Makeup Professionali",
        description="Set di pennelli trucco con custodia, pensato per routine makeup completa e precisa",
        price=18.99,
        original_price=37.99,
        discount=50,
        category=DealCategory.beauty,
        image_url="https://example.com/makeup-brush-set.jpg",
        url="https://example.com/deal/15",
    ),
    Deal(
        id=16,
        title="Kit Skincare Base Quotidiana",
        description="Cofanetto con detergente viso, tonico e crema idratante per cura della pelle semplice e completa",
        price=34.99,
        original_price=69.99,
        discount=50,
        category=DealCategory.beauty,
        image_url="https://example.com/basic-skincare-kit.jpg",
        url="https://example.com/deal/16",
    ),
    Deal(
        id=17,
        title="Balsamo Labbra Nutriente",
        description="Balsamo labbra idratante con ingredienti naturali, ideale per chi ama prodotti beauty minimal",
        price=7.99,
        original_price=14.99,
        discount=47,
        category=DealCategory.beauty,
        image_url="https://example.com/lip-balm.jpg",
        url="https://example.com/deal/17",
    ),
    Deal(
        id=18,
        title="Crema Mani Riparatrice",
        description="Crema mani intensiva per pelle secca, perfetta per routine benessere quotidiana",
        price=9.99,
        original_price=19.99,
        discount=50,
        category=DealCategory.beauty,
        image_url="https://example.com/hand-cream.jpg",
        url="https://example.com/deal/18",
    ),
    Deal(
        id=19,
        title="Scrub Corpo Delicato",
        description="Scrub corpo con granuli fini, lascia la pelle liscia e pronta ai trattamenti skincare",
        price=16.99,
        original_price=33.99,
        discount=50,
        category=DealCategory.beauty,
        image_url="https://example.com/body-scrub.jpg",
        url="https://example.com/deal/19",
    ),
    Deal(
        id=20,
        title="Set Maschere in Tessuto",
        description="Confezione di maschere viso in tessuto per skincare rilassante e momenti spa a casa",
        price=14.99,
        original_price=29.99,
        discount=50,
        category=DealCategory.beauty,
        image_url="https://example.com/sheet-masks.jpg",
        url="https://example.com/deal/20",
    ),

    # ===== HOME =====
    Deal(
        id=21,
        title="Robot Aspirapolvere Smart",
        description="Aspirapolvere robot con mappatura intelligente, ideale per casa con animali e pavimenti misti",
        price=199.99,
        original_price=399.99,
        discount=50,
        category=DealCategory.home,
        image_url="https://example.com/robot-vacuum.jpg",
        url="https://example.com/deal/21",
    ),
    Deal(
        id=22,
        title="Lampada LED Intelligente RGB",
        description="Lampada smart con controllo da app, scenari luminosi e atmosfera per salotto moderno",
        price=22.99,
        original_price=45.99,
        discount=50,
        category=DealCategory.home,
        image_url="https://example.com/smart-lamp.jpg",
        url="https://example.com/deal/22",
    ),
    Deal(
        id=23,
        title="Termostato Intelligente WiFi",
        description="Termostato connesso per gestione riscaldamento, pensato per casa efficiente e consumo ridotto",
        price=79.99,
        original_price=159.99,
        discount=50,
        category=DealCategory.home,
        image_url="https://example.com/smart-thermostat.jpg",
        url="https://example.com/deal/23",
    ),
    Deal(
        id=24,
        title="Set Tessili Bagno Premium",
        description="Set di asciugamani e tappeti bagno in cotone morbido, ideale per arredare casa in modo accogliente",
        price=49.99,
        original_price=99.99,
        discount=50,
        category=DealCategory.home,
        image_url="https://example.com/bath-textiles.jpg",
        url="https://example.com/deal/24",
    ),
    Deal(
        id=25,
        title="Diffusore Aromi Ultrasonico",
        description="Diffusore aromi con luci soffuse, perfetto per creare atmosfera rilassante in casa",
        price=24.99,
        original_price=49.99,
        discount=50,
        category=DealCategory.home,
        image_url="https://example.com/aroma-diffuser.jpg",
        url="https://example.com/deal/25",
    ),
    Deal(
        id=26,
        title="Set Coperte Morbide da Divano",
        description="Coperte in pile morbido per serate sul divano, ideali in salotto o camera da letto",
        price=39.99,
        original_price=79.99,
        discount=50,
        category=DealCategory.home,
        image_url="https://example.com/sofa-blankets.jpg",
        url="https://example.com/deal/26",
    ),
    Deal(
        id=27,
        title="Set Candele Profumate Casa",
        description="Candele con profumazioni delicate per creare atmosfera, perfette per regali casa e arredo",
        price=19.99,
        original_price=39.99,
        discount=50,
        category=DealCategory.home,
        image_url="https://example.com/home-candles.jpg",
        url="https://example.com/deal/27",
    ),
    Deal(
        id=28,
        title="Organizer Armadio Modulabile",
        description="Set organizer per armadio e guardaroba, aiuta a mantenere la casa ordinata",
        price=29.99,
        original_price=59.99,
        discount=50,
        category=DealCategory.home,
        image_url="https://example.com/closet-organizer.jpg",
        url="https://example.com/deal/28",
    ),
    Deal(
        id=29,
        title="Set Piatti in Ceramica Colorata",
        description="Servizio piatti per la casa, stile moderno, perfetto per tavola quotidiana e cene con amici",
        price=59.99,
        original_price=119.99,
        discount=50,
        category=DealCategory.home,
        image_url="https://example.com/colorful-plates.jpg",
        url="https://example.com/deal/29",
    ),
    Deal(
        id=30,
        title="Kit Accessori Cucina Essenziali",
        description="Set utensili cucina di base per chi arreda una nuova casa o aggiorna i propri accessori",
        price=34.99,
        original_price=69.99,
        discount=50,
        category=DealCategory.home,
        image_url="https://example.com/kitchen-kit.jpg",
        url="https://example.com/deal/30",
    ),

    # ===== TOYS =====
    Deal(
        id=31,
        title="Gioco Costruzioni Magnetiche",
        description="Set di costruzioni magnetiche colorate, stimola creatività e logica nei bambini",
        price=34.99,
        original_price=69.99,
        discount=50,
        category=DealCategory.toys,
        image_url="https://example.com/magnetic-blocks.jpg",
        url="https://example.com/deal/31",
    ),
    Deal(
        id=32,
        title="Robot Educativo Programmabile",
        description="Robot giocattolo programmabile per introdurre il coding ai più piccoli con gioco interattivo",
        price=59.99,
        original_price=119.99,
        discount=50,
        category=DealCategory.toys,
        image_url="https://example.com/educational-robot.jpg",
        url="https://example.com/deal/32",
    ),
    Deal(
        id=33,
        title="Pattini a Rotelle Regolabili",
        description="Pattini regolabili con protezioni, ideali per bambini attivi e giochi all'aperto in sicurezza",
        price=54.99,
        original_price=109.99,
        discount=50,
        category=DealCategory.toys,
        image_url="https://example.com/roller-skates.jpg",
        url="https://example.com/deal/33",
    ),
    Deal(
        id=34,
        title="Telescopio Osservazione Stellare",
        description="Telescopio per osservare luna e stelle, perfetto per bambini curiosi e famiglie",
        price=64.99,
        original_price=129.99,
        discount=50,
        category=DealCategory.toys,
        image_url="https://example.com/telescope.jpg",
        url="https://example.com/deal/34",
    ),
    Deal(
        id=35,
        title="Set Giochi da Tavolo Famiglia",
        description="Selezione di giochi da tavolo semplici, ideale per serate in famiglia e amici",
        price=39.99,
        original_price=79.99,
        discount=50,
        category=DealCategory.toys,
        image_url="https://example.com/family-boardgames.jpg",
        url="https://example.com/deal/35",
    ),
    Deal(
        id=36,
        title="Puzzle 1000 Pezzi Panorama",
        description="Puzzle panoramico da 1000 pezzi, perfetto per chi ama giochi di pazienza e relax",
        price=24.99,
        original_price=49.99,
        discount=50,
        category=DealCategory.toys,
        image_url="https://example.com/panorama-puzzle.jpg",
        url="https://example.com/deal/36",
    ),
    Deal(
        id=37,
        title="Set Matite Colorate Artista",
        description="Set matite colorate di qualità, ideale per bambini creativi e disegno artistico",
        price=19.99,
        original_price=39.99,
        discount=50,
        category=DealCategory.toys,
        image_url="https://example.com/artist-pencils.jpg",
        url="https://example.com/deal/37",
    ),
    Deal(
        id=38,
        title="Kit Laboratorio Scientifico Junior",
        description="Gioco educativo con esperimenti semplici, perfetto per bambini curiosi di scienza",
        price=29.99,
        original_price=59.99,
        discount=50,
        category=DealCategory.toys,
        image_url="https://example.com/science-lab-kit.jpg",
        url="https://example.com/deal/38",
    ),
    Deal(
        id=39,
        title="Peluche Animale Morbido",
        description="Peluche soffice e lavabile, ideale come regalo per bambini piccoli",
        price=14.99,
        original_price=29.99,
        discount=50,
        category=DealCategory.toys,
        image_url="https://example.com/soft-plush.jpg",
        url="https://example.com/deal/39",
    ),
    Deal(
        id=40,
        title="Set Macchinine da Corsa",
        description="Confezione di piccole auto giocattolo, perfetta per giochi di fantasia su pista",
        price=17.99,
        original_price=35.99,
        discount=50,
        category=DealCategory.toys,
        image_url="https://example.com/racing-cars.jpg",
        url="https://example.com/deal/40",
    ),

    # ===== FASHION =====
    Deal(
        id=41,
        title="Giacca Invernale Impermeabile",
        description="Giacca invernale con imbottitura leggera, ideale per chi cerca moda e praticità",
        price=89.99,
        original_price=179.99,
        discount=50,
        category=DealCategory.fashion,
        image_url="https://example.com/winter-jacket.jpg",
        url="https://example.com/deal/41",
    ),
    Deal(
        id=42,
        title="Sneakers Running Leggere",
        description="Scarpe sportive leggere e ammortizzate, perfette per corsa e tempo libero",
        price=74.99,
        original_price=149.99,
        discount=50,
        category=DealCategory.fashion,
        image_url="https://example.com/running-shoes.jpg",
        url="https://example.com/deal/42",
    ),
    Deal(
        id=43,
        title="Zaino Laptop Ergonomico",
        description="Zaino con scomparto imbottito per laptop, adatto a lavoro, università e viaggio",
        price=39.99,
        original_price=79.99,
        discount=50,
        category=DealCategory.fashion,
        image_url="https://example.com/laptop-backpack.jpg",
        url="https://example.com/deal/43",
    ),
    Deal(
        id=44,
        title="Cintura in Pelle Naturale",
        description="Cintura classica in pelle liscia, accessorio moda versatile per uso quotidiano",
        price=29.99,
        original_price=59.99,
        discount=50,
        category=DealCategory.fashion,
        image_url="https://example.com/leather-belt.jpg",
        url="https://example.com/deal/44",
    ),
    Deal(
        id=45,
        title="Beanie Lana Morbida",
        description="Berretto in lana morbida, perfetto per look casual invernale",
        price=19.99,
        original_price=39.99,
        discount=50,
        category=DealCategory.fashion,
        image_url="https://example.com/wool-beanie.jpg",
        url="https://example.com/deal/45",
    ),
    Deal(
        id=46,
        title="Sciarpa Lunga a Maglia",
        description="Sciarpa lunga in maglia, aggiunge stile e calore agli outfit invernali",
        price=24.99,
        original_price=49.99,
        discount=50,
        category=DealCategory.fashion,
        image_url="https://example.com/knitted-scarf.jpg",
        url="https://example.com/deal/46",
    ),
    Deal(
        id=47,
        title="Set Calze Fantasia Colorate",
        description="Pacco di calze con fantasie colorate, idea regalo moda divertente",
        price=14.99,
        original_price=29.99,
        discount=50,
        category=DealCategory.fashion,
        image_url="https://example.com/colorful-socks.jpg",
        url="https://example.com/deal/47",
    ),
    Deal(
        id=48,
        title="Portafoglio Compatibile RFID",
        description="Portafoglio compatto con protezione RFID, pensato per uso quotidiano e viaggi",
        price=34.99,
        original_price=69.99,
        discount=50,
        category=DealCategory.fashion,
        image_url="https://example.com/rfid-wallet.jpg",
        url="https://example.com/deal/48",
    ),
    Deal(
        id=49,
        title="Camicia Casual in Cotone",
        description="Camicia in cotone dal taglio regolare, adatta a ufficio e tempo libero",
        price=39.99,
        original_price=79.99,
        discount=50,
        category=DealCategory.fashion,
        image_url="https://example.com/casual-shirt.jpg",
        url="https://example.com/deal/49",
    ),
    Deal(
        id=50,
        title="Borsa Tracolla Minimal",
        description="Borsa tracolla dallo stile minimal, ideale per chi cerca moda essenziale",
        price=59.99,
        original_price=119.99,
        discount=50,
        category=DealCategory.fashion,
        image_url="https://example.com/minimal-crossbody-bag.jpg",
        url="https://example.com/deal/50",
    ),
]


def get_all_deals() -> List[Deal]:
    """Restituisce la lista completa di tutti i prodotti."""
    return DEALS


def get_deals_by_category(category: DealCategory) -> List[Deal]:
    """Filtra i prodotti per categoria."""
    return [deal for deal in DEALS if deal.category == category]


def search_deals_by_keyword(keyword: str) -> List[Deal]:
    """Ricerca prodotti per parola chiave in titolo e descrizione."""
    keyword_lower = keyword.lower()
    return [
        deal
        for deal in DEALS
        if keyword_lower in deal.title.lower() or keyword_lower in deal.description.lower()
    ]
